version: 1

update_configs:
  - package_manager: "ruby:bundler"
    directory: "/"
    update_schedule: "live"
    default_assignees:
    - jalyna

  - package_manager: "javascript"
    directory: "/test/dummy/"
    update_schedule: "live"
    default_assignees:
    - jalyna
